### ISSUE TITLE
中文字符被识别成emoji的问题

### ISSUE THREAD

**Issue by HuParry** [noneplugin/nonebot-plugin-emojimix#3]
为了方便，我把加号给删去了，然后偶然间发现了问题，那就是“好”会被识别成emoji，如图。这样的问题我不知道该如何解决。是正则表达式的bug吗？
![Uploading A8B0646E-9A54-4A7E-B959-D5F6DDFB500B.jpeg…]()

**Comment by HuParry** [comment]
![Uploading EE131316-B5EA-48F2-93F4-96F6521742AE.jpeg…]()

**Comment by MeetWq** [comment]
图片看不到

**Comment by MeetWq** [comment]
确实有问题，试试新版本

**Comment by HuParry** [comment]
谢谢，刚刚试了一下，暂时没发现问题了，感谢更改。
